### ISSUE TITLE
Availability in CocoaPods?

### ISSUE THREAD

**Issue by gams95** [NetcoreSolutions/SmartPush-iOS-SDK#1]
Hi i've been trying to install this package using cocoapods but it seems that the latest version is not available. Was this intended?

**Comment by mmgmail** [comment]
Not available from cocoapods, fix please

**Comment by icodebuster** [comment]
@gams95 @mmgmail The version was released last week. 

The pod spec it available with Cocoapods: check [here](https://github.com/CocoaPods/Specs/blob/master/Specs/a/c/3/SmartPush-iOS-SDK/3.2.0/SmartPush-iOS-SDK.podspec.json) 

Added it to a demo project it's working as expected.
<img width="965" alt="image" src="https://user-images.githubusercontent.com/1160545/229877979-bd574c25-3ee9-4de0-ab33-023cc492f06f.png">

You can run this command on your terminal 
`pod search SmartPush-iOS-SDK`

You will see something similar to the one below.
<img width="746" alt="image" src="https://user-images.githubusercontent.com/1160545/229878758-a3fea591-e064-498e-8478-0699e3c916fe.png">
