### ISSUE TITLE
Availability on M1 Mac Simulator

### ISSUE THREAD

**Issue by gams95** [NetcoreSolutions/SmartPush-iOS-SDK#2]
Hi Im trying to build for iOS Simulator on M1 Mac but it failed to build saying that

 ```Building for iOS Simulator, but linking in dylib built for iOS, file '[PROJECT_NAME]/Pods/SmartPush-iOS-SDK/Frameworks/SmartPush/SmartPush.framework/SmartPush' for architecture arm64```
 
 Any idea whats the issue?

**Comment by icodebuster** [comment]
@gams95, which SDK version are you using? The latest version is [3.2.1](https://github.com/NetcoreSolutions/SmartPush-iOS-SDK/releases/tag/v3.2.1)

**Comment by gams95** [comment]
@icodebuster I'm using v 1.0.0 Will try to update it and see how it goes
